### ISSUE TITLE
Subscription Support

### ISSUE THREAD

**Issue by erandagan** [bluesnap/bluesnap-android-int#3]
It seems as if the SDK only supports one time transactions, with a fixed amount and such. 

Are subscriptions a planned feature? The Payment API supports these, but often requires redirects to mobile-web sites.

**Comment by RYBR** [comment]
The SDK's checkout page is design for a one-time-charge.
But there is no limitation with using the SDK for subscriptions, since subscriptions in the Payment-API works with the same token as one-time-charge.

So you can use the SDK to collect the shopper's information and to finish the transaction you can just do a create-subscription call instead of create-transaction.

For more information on this please contact Support

**Comment by snpori** [comment]
Subscription is now supported
